import = ["~/.config/alacritty/themes/themes/github_dark.toml"]

[font]
size = 18

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.8
#decorations = "none"
blur = true

[window.padding]
x = 7
y = 0
